spring:
  datasource:
    url: jdbc:postgresql://ml-postgres:5432/docker
  zipkin:
    base-url: http://ml-zipkin:9411

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://ml-discovery:8761}/eureka/

