server:
  port: ${PORT:3001}

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/docker
    username: docker
    password: XOzaMGE68L5t
    platform: POSTGRESQL
  jpa:
    show-sql: true
  zipkin:
    base-url: http://localhost:9411

eureka:
  client:
    serviceUrl:
      defaultZone: ${DISCOVERY_URL:http://localhost:8761}/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

ribbon:
  eureka:
    enabled: true
