version: '2.0'

services:
  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch
    restart: always
    ports:
      - "9200:9200"

  kibana:
    container_name: kibana
    image: kibana
    restart: always
    ports:
      - "5601:5601"

  logstash:
    container_name: logstash
    image: logstash
    command: logstash -e 'input { tcp { port => 5000 codec => "json" } } output { elasticsearch { hosts => ["elasticsearch:9200"] index => "micro-%{serviceName}"} }'
    restart: always
    ports:
      - "5000:5000"

  ml-customer:
    container_name: ml-customer
    image: alaxat/ml-customer
    restart: always
    ports:
      - "2001:3001"

  ml-order:
    hostname: ml-order
    container_name: ml-order
    image: alaxat/ml-order
    restart: always
    ports:
      - "2002:3001"

  ml-discovery:
    container_name: ml-discovery
    image: alaxat/ml-discovery
    restart: always
    ports:
      - "8761:8761"

  ml-zipkin:
    container_name: ml-zipkin
    image: alaxat/ml-zipkin
    restart: always
    ports:
      - "9411:9411"

  ml-mongo:
    container_name: ml-mongo
    image: alaxat/ml-mongo
    restart: always
    ports:
      - "26000:27017"
    environment:
      INIT_DUMP: test-dump.js
      MONGODB_PASSWORD: abc

  ml-postgres:
    container_name: ml-postgres
    image: alaxat/ml-postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: docker
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: XOzaMGE68L5t
#      POSTGRES_INITDB_ARGS: "--auth=md5 --pwfile=/tmp/pgpass"